export const races = [
  { id: 1, name: "Trail des Flandres", location: "Bailleul", region: "Hauts-de-France", date: "2026-04-18", distanceKm: 42, elevationGainM: 950, terrainType: "Mixte", technicalityLevel: "Modérée", cutoffTimeMinutes: 600, lastFinisherTimeMinutes: 572, medianFinisherTimeMinutes: 430, aidStationsCount: 4, priceEur: 48, description: "Trail vallonné typique des Flandres, alternant chemins agricoles, sentiers boisés, montées courtes et passages potentiellement boueux.", tags: ["Idéal reprise", "Barrières larges"], gradient: "from-emerald-900 via-lime-700 to-orange-300" },
  { id: 2, name: "Ultra Vosgien", location: "Gérardmer", region: "Grand Est", date: "2026-06-27", distanceKm: 72, elevationGainM: 3200, terrainType: "Montagne", technicalityLevel: "Difficile", cutoffTimeMinutes: 960, lastFinisherTimeMinutes: 942, medianFinisherTimeMinutes: 760, aidStationsCount: 7, priceEur: 92, description: "Parcours exigeant de moyenne montagne, avec longues montées, descentes techniques et gestion de l’effort sur la durée.", tags: ["Prépa ultra", "Technique"], gradient: "from-slate-900 via-emerald-800 to-cyan-300" },
  { id: 3, name: "Marathon des Crêtes", location: "Le Tholy", region: "Grand Est", date: "2026-09-20", distanceKm: 42, elevationGainM: 1900, terrainType: "Montagne", technicalityLevel: "Soutenue", cutoffTimeMinutes: 510, lastFinisherTimeMinutes: 478, medianFinisherTimeMinutes: 380, aidStationsCount: 5, priceEur: 55, description: "Format marathon très dense en dénivelé, adapté aux coureurs déjà à l’aise sur terrain technique et descentes longues.", tags: ["Technique", "Crêtes"], gradient: "from-stone-900 via-orange-700 to-amber-300" },
  { id: 4, name: "Trail des Flandres Ultra", location: "Bailleul", region: "Hauts-de-France", date: "2026-04-18", distanceKm: 115, elevationGainM: 2800, terrainType: "Mixte", technicalityLevel: "Difficile", cutoffTimeMinutes: 1440, lastFinisherTimeMinutes: 1395, medianFinisherTimeMinutes: 1120, aidStationsCount: 10, priceEur: 125, description: "Ultra long et usant, moins montagneux qu’un alpin mais exigeant par la durée, la météo possible et la répétition des relances.", tags: ["Ultra", "Gestion chrono"], gradient: "from-emerald-950 via-emerald-700 to-lime-300" },
  { id: 5, name: "SaintéLyon", location: "Saint-Étienne → Lyon", region: "Auvergne-Rhône-Alpes", date: "2026-12-05", distanceKm: 78, elevationGainM: 2100, terrainType: "Nocturne", technicalityLevel: "Soutenue", cutoffTimeMinutes: 960, lastFinisherTimeMinutes: 940, medianFinisherTimeMinutes: 710, aidStationsCount: 6, priceEur: 98, description: "Course mythique de nuit, roulante par moments mais piégeuse par le froid, la fatigue et les longues portions nocturnes.", tags: ["Nocturne", "Mythique"], gradient: "from-indigo-950 via-slate-800 to-orange-300" },
  { id: 6, name: "Trail du Jura", location: "Les Rousses", region: "Bourgogne-Franche-Comté", date: "2026-07-11", distanceKm: 55, elevationGainM: 2400, terrainType: "Montagne", technicalityLevel: "Difficile", cutoffTimeMinutes: 720, lastFinisherTimeMinutes: 698, medianFinisherTimeMinutes: 545, aidStationsCount: 5, priceEur: 69, description: "Format intermédiaire parfait pour progresser vers le long, avec un ratio D+/km sérieux et un terrain parfois cassant.", tags: ["Étape intermédiaire", "D+"], gradient: "from-sky-950 via-emerald-700 to-lime-200" },
  {
    id: 7,
    name: "Trail du Patois - 29 km",
    location: "Olhain",
    region: "Hauts-de-France",
    date: "2026-05-03",
    distanceKm: 29,
    elevationGainM: 700,
    terrainType: "Forêt / Terrils",
    technicalityLevel: "Modérée",
    cutoffTimeMinutes: 360,
    lastFinisherTimeMinutes: 335,
    medianFinisherTimeMinutes: 250,
    aidStationsCount: 2,
    priceEur: 28,
    description: "Trail court vallonné dans le Pas-de-Calais, intéressant pour travailler les relances, les chemins forestiers et les montées courtes.",
    tags: ["Hauts-de-France", "Relances", "Accessible"],
    gradient: "from-lime-950 via-green-700 to-yellow-300"
  },
  {
    id: 8,
    name: "Trail des Pyramides Noires - 70 km",
    location: "Oignies",
    region: "Hauts-de-France",
    date: "2026-05-09",
    distanceKm: 70,
    elevationGainM: 1000,
    terrainType: "Terrils / Urbain / Nature",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 780,
    lastFinisherTimeMinutes: 735,
    medianFinisherTimeMinutes: 580,
    aidStationsCount: 5,
    priceEur: 75,
    description: "Long trail atypique dans le bassin minier, alternant terrils, friches, chemins urbains et portions roulantes.",
    tags: ["Terrils", "Long", "Bassin minier"],
    gradient: "from-zinc-950 via-stone-700 to-amber-400"
  },
  {
    id: 9,
    name: "Trail des Hobbits - Mara-Comtoise",
    location: "La Comté",
    region: "Hauts-de-France",
    date: "2026-06-06",
    distanceKm: 42,
    elevationGainM: 850,
    terrainType: "Forêt / Champs",
    technicalityLevel: "Modérée",
    cutoffTimeMinutes: 540,
    lastFinisherTimeMinutes: 505,
    medianFinisherTimeMinutes: 365,
    aidStationsCount: 4,
    priceEur: 42,
    description: "Trail forestier et vallonné, bon format marathon pour progresser sans entrer dans un terrain de montagne.",
    tags: ["Marathon trail", "Forêt", "Progressif"],
    gradient: "from-green-950 via-emerald-700 to-lime-300"
  },
  {
    id: 10,
    name: "Trail National Côte d’Opale - 42 km",
    location: "Wimereux",
    region: "Hauts-de-France",
    date: "2026-09-13",
    distanceKm: 42,
    elevationGainM: 840,
    terrainType: "Littoral / Sable / Falaises",
    technicalityLevel: "Modérée",
    cutoffTimeMinutes: 570,
    lastFinisherTimeMinutes: 540,
    medianFinisherTimeMinutes: 390,
    aidStationsCount: 4,
    priceEur: 55,
    description: "Trail côtier très populaire, alternant sable, sentiers littoraux, falaises et portions roulantes.",
    tags: ["Littoral", "Sable", "Populaire"],
    gradient: "from-sky-950 via-cyan-700 to-yellow-300"
  },
  {
    id: 11,
    name: "Trail National Côte d’Opale - Ultra 110 km",
    location: "Wimereux",
    region: "Hauts-de-France",
    date: "2026-09-13",
    distanceKm: 110,
    elevationGainM: 1300,
    terrainType: "Littoral / Sable / Falaises",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1440,
    lastFinisherTimeMinutes: 1370,
    medianFinisherTimeMinutes: 1080,
    aidStationsCount: 8,
    priceEur: 120,
    description: "Ultra côtier long et usant, avec une difficulté venant surtout de la durée, du sable, du vent et de la répétition des relances.",
    tags: ["Ultra", "Côte d’Opale", "Gestion chrono"],
    gradient: "from-blue-950 via-slate-700 to-orange-300"
  },
  {
    id: 12,
    name: "Trail Alsace by UTMB - Ultra-Trail des Païens",
    location: "Orschwiller → Obernai",
    region: "Grand Est",
    date: "2026-05-15",
    distanceKm: 108,
    elevationGainM: 3900,
    terrainType: "Vosges / Forêt / Châteaux",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1440,
    lastFinisherTimeMinutes: 1370,
    medianFinisherTimeMinutes: 1080,
    aidStationsCount: 8,
    priceEur: 150,
    description: "Format 100K exigeant entre massif vosgien, forêts, villages alsaciens et châteaux.",
    tags: ["UTMB Index", "Vosges", "100K"],
    gradient: "from-slate-950 via-emerald-800 to-amber-300"
  },
  {
    id: 13,
    name: "Trail Alsace by UTMB - Trail des Celtes",
    location: "Barr",
    region: "Grand Est",
    date: "2026-05-17",
    distanceKm: 47,
    elevationGainM: 1600,
    terrainType: "Vosges / Forêt",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 600,
    lastFinisherTimeMinutes: 570,
    medianFinisherTimeMinutes: 420,
    aidStationsCount: 4,
    priceEur: 80,
    description: "Format 50K idéal pour découvrir les Vosges avec un dénivelé sérieux mais encore maîtrisable.",
    tags: ["50K", "Vosges", "Forêt"],
    gradient: "from-emerald-950 via-teal-700 to-lime-300"
  },
  {
    id: 14,
    name: "Ultra Marin - Grand Raid",
    location: "Vannes",
    region: "Bretagne",
    date: "2026-06-26",
    distanceKm: 175,
    elevationGainM: 1430,
    terrainType: "Côtier / Roulant",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 2520,
    lastFinisherTimeMinutes: 2420,
    medianFinisherTimeMinutes: 1900,
    aidStationsCount: 12,
    priceEur: 180,
    description: "Très long ultra autour du Golfe du Morbihan, relativement roulant mais redoutable par la durée, la nuit et la gestion mentale.",
    tags: ["Ultra long", "Bretagne", "Roulant"],
    gradient: "from-cyan-950 via-blue-800 to-lime-300"
  },
  {
    id: 15,
    name: "Ultra Marin - Raid 100 km",
    location: "Vannes",
    region: "Bretagne",
    date: "2026-06-25",
    distanceKm: 100,
    elevationGainM: 540,
    terrainType: "Côtier / Roulant",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 1200,
    lastFinisherTimeMinutes: 1140,
    medianFinisherTimeMinutes: 880,
    aidStationsCount: 7,
    priceEur: 110,
    description: "Format 100 km roulant autour du Golfe, intéressant pour tester une stratégie d’ultra sans gros dénivelé.",
    tags: ["100K", "Roulant", "Gestion allure"],
    gradient: "from-sky-950 via-cyan-700 to-emerald-300"
  },
  {
    id: 16,
    name: "Trail de Guerlédan - 70 km",
    location: "Guerlédan",
    region: "Bretagne",
    date: "2026-05-24",
    distanceKm: 70,
    elevationGainM: 2700,
    terrainType: "Forêt / Lac / Racines",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 900,
    lastFinisherTimeMinutes: 855,
    medianFinisherTimeMinutes: 690,
    aidStationsCount: 6,
    priceEur: 85,
    description: "Trail breton réputé autour du lac de Guerlédan, technique par ses racines, ses sous-bois et ses relances.",
    tags: ["Bretagne", "Technique", "Forêt"],
    gradient: "from-green-950 via-teal-800 to-cyan-300"
  },
  {
    id: 17,
    name: "Trail de Sancerre - La Magnum",
    location: "Sancerre",
    region: "Centre-Val de Loire",
    date: "2026-06-13",
    distanceKm: 35,
    elevationGainM: 1000,
    terrainType: "Vignes / Coteaux",
    technicalityLevel: "Modérée",
    cutoffTimeMinutes: 360,
    lastFinisherTimeMinutes: 345,
    medianFinisherTimeMinutes: 285,
    aidStationsCount: 3,
    priceEur: 41,
    description: "Trail vallonné au cœur du vignoble de Sancerre, avec des coteaux exigeants mais un format encore accessible.",
    tags: ["Vignes", "Coteaux", "Accessible"],
    gradient: "from-purple-950 via-fuchsia-700 to-amber-300"
  },
  {
    id: 18,
    name: "MaXi-Race Annecy - tOur du Lac Solo",
    location: "Annecy",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-30",
    distanceKm: 103,
    elevationGainM: 5900,
    terrainType: "Montagne / Lac",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1620,
    lastFinisherTimeMinutes: 1540,
    medianFinisherTimeMinutes: 1240,
    aidStationsCount: 8,
    priceEur: 160,
    description: "Tour du lac d’Annecy par les montagnes, très exigeant par son ratio distance/D+ et ses longues descentes.",
    tags: ["Annecy", "Ultra", "Montagne"],
    gradient: "from-sky-950 via-indigo-800 to-lime-300"
  },
  {
    id: 19,
    name: "MaXi-Race Annecy - Demi tOur du Lac",
    location: "Annecy",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-31",
    distanceKm: 55,
    elevationGainM: 3300,
    terrainType: "Montagne / Lac",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 780,
    lastFinisherTimeMinutes: 735,
    medianFinisherTimeMinutes: 590,
    aidStationsCount: 5,
    priceEur: 95,
    description: "Format montagne dense en dénivelé, parfait pour tester sa capacité à encaisser montée et descente sur terrain alpin.",
    tags: ["Montagne", "D+", "Annecy"],
    gradient: "from-blue-950 via-cyan-800 to-lime-200"
  },
  {
    id: 20,
    name: "Marathon du Mont-Blanc - 42 km",
    location: "Chamonix",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-06-28",
    distanceKm: 42,
    elevationGainM: 2540,
    terrainType: "Montagne",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 600,
    lastFinisherTimeMinutes: 570,
    medianFinisherTimeMinutes: 455,
    aidStationsCount: 4,
    priceEur: 80,
    description: "Course mythique de montagne à Chamonix, très dense en dénivelé pour un format marathon.",
    tags: ["Chamonix", "Montagne", "Mythique"],
    gradient: "from-slate-950 via-sky-800 to-white"
  },
  {
    id: 21,
    name: "Marathon du Mont-Blanc - 23 km",
    location: "Chamonix",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-06-27",
    distanceKm: 23,
    elevationGainM: 1680,
    terrainType: "Montagne",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 360,
    lastFinisherTimeMinutes: 335,
    medianFinisherTimeMinutes: 260,
    aidStationsCount: 2,
    priceEur: 55,
    description: "Format court mais très montagneux, idéal pour jauger son aisance en montée longue.",
    tags: ["23K", "Montagne", "D+"],
    gradient: "from-cyan-950 via-blue-700 to-slate-200"
  },
  {
    id: 22,
    name: "OCC - UTMB Mont-Blanc",
    location: "Orsières → Chamonix",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-08-27",
    distanceKm: 57,
    elevationGainM: 3500,
    terrainType: "Alpin",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 870,
    lastFinisherTimeMinutes: 835,
    medianFinisherTimeMinutes: 650,
    aidStationsCount: 5,
    priceEur: 140,
    description: "Finale 50K UTMB World Series, très exigeante avec un profil alpin et une arrivée mythique à Chamonix.",
    tags: ["UTMB", "Alpin", "50K"],
    gradient: "from-slate-950 via-blue-800 to-orange-300"
  },
  {
    id: 23,
    name: "CCC - UTMB Mont-Blanc",
    location: "Courmayeur → Chamonix",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-08-28",
    distanceKm: 101,
    elevationGainM: 6050,
    terrainType: "Alpin",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1560,
    lastFinisherTimeMinutes: 1490,
    medianFinisherTimeMinutes: 1220,
    aidStationsCount: 8,
    priceEur: 220,
    description: "Grand classique autour du Mont-Blanc, très exigeant par le dénivelé, l’altitude et la densité du plateau.",
    tags: ["UTMB", "100K", "Alpin"],
    gradient: "from-zinc-950 via-indigo-800 to-sky-300"
  },
  {
    id: 24,
    name: "UTMB Mont-Blanc",
    location: "Chamonix",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-08-28",
    distanceKm: 171,
    elevationGainM: 10000,
    terrainType: "Alpin",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 2760,
    lastFinisherTimeMinutes: 2650,
    medianFinisherTimeMinutes: 2200,
    aidStationsCount: 11,
    priceEur: 355,
    description: "Référence mondiale de l’ultra-trail, tour complet du Mont-Blanc entre France, Italie et Suisse.",
    tags: ["Mythique", "100M", "Extrême"],
    gradient: "from-black via-slate-800 to-cyan-300"
  },
  {
    id: 25,
    name: "Grand Raid des Pyrénées - Ultra Tour",
    location: "Vielle-Aure",
    region: "Occitanie",
    date: "2026-08-21",
    distanceKm: 160,
    elevationGainM: 10000,
    terrainType: "Montagne",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 3000,
    lastFinisherTimeMinutes: 2880,
    medianFinisherTimeMinutes: 2350,
    aidStationsCount: 12,
    priceEur: 240,
    description: "Ultra pyrénéen majeur, long, engagé et très dense en dénivelé.",
    tags: ["Pyrénées", "Ultra", "D+ massif"],
    gradient: "from-stone-950 via-red-800 to-yellow-300"
  },
  {
    id: 26,
    name: "Grand Raid des Pyrénées - Tour des Cirques",
    location: "Piau-Engaly",
    region: "Occitanie",
    date: "2026-08-21",
    distanceKm: 120,
    elevationGainM: 7500,
    terrainType: "Montagne",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 2400,
    lastFinisherTimeMinutes: 2300,
    medianFinisherTimeMinutes: 1850,
    aidStationsCount: 9,
    priceEur: 190,
    description: "Format très montagneux dans les Pyrénées, avec une difficulté majeure liée au ratio D+/km.",
    tags: ["Pyrénées", "Technique", "120K"],
    gradient: "from-slate-950 via-orange-800 to-amber-300"
  },
  {
    id: 27,
    name: "Restonica Trail by UTMB - 67 km",
    location: "Corte",
    region: "Corse",
    date: "2026-07-11",
    distanceKm: 67,
    elevationGainM: 3900,
    terrainType: "Montagne / Corse",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1140,
    lastFinisherTimeMinutes: 1090,
    medianFinisherTimeMinutes: 860,
    aidStationsCount: 6,
    priceEur: 90,
    description: "Trail corse technique entre lacs, crêtes et sentiers exigeants autour de Corte.",
    tags: ["Corse", "Technique", "Montagne"],
    gradient: "from-orange-950 via-red-700 to-sky-300"
  },
  {
    id: 28,
    name: "Restonica Ultra-Trail - 110 km",
    location: "Corte",
    region: "Corse",
    date: "2026-07-09",
    distanceKm: 110,
    elevationGainM: 7200,
    terrainType: "Montagne / Corse",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 2100,
    lastFinisherTimeMinutes: 2020,
    medianFinisherTimeMinutes: 1650,
    aidStationsCount: 8,
    priceEur: 130,
    description: "Ultra très technique en Corse, exigeant autant par le dénivelé que par la nature du terrain.",
    tags: ["Corse", "Ultra", "Extrême"],
    gradient: "from-stone-950 via-orange-800 to-cyan-300"
  },
  {
    id: 29,
    name: "Trail des Passerelles du Monteynard - Grande Course",
    location: "Treffort",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-07-12",
    distanceKm: 63,
    elevationGainM: 3000,
    terrainType: "Montagne / Lac / Passerelles",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 840,
    lastFinisherTimeMinutes: 800,
    medianFinisherTimeMinutes: 640,
    aidStationsCount: 5,
    priceEur: 80,
    description: "Trail spectaculaire autour du lac de Monteynard avec passages sur passerelles himalayennes.",
    tags: ["Passerelles", "Lac", "Montagne"],
    gradient: "from-teal-950 via-cyan-700 to-lime-300"
  },
  {
    id: 30,
    name: "Trail des Passerelles du Monteynard - Maratrail",
    location: "Treffort",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-07-12",
    distanceKm: 40,
    elevationGainM: 1900,
    terrainType: "Montagne / Lac",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 570,
    lastFinisherTimeMinutes: 540,
    medianFinisherTimeMinutes: 420,
    aidStationsCount: 4,
    priceEur: 55,
    description: "Format marathon autour du Monteynard, bon compromis entre beauté du parcours et exigence montagne.",
    tags: ["Maratrail", "Lac", "D+"],
    gradient: "from-cyan-950 via-blue-700 to-emerald-300"
  },
  {
    id: 31,
    name: "UT4M - 180 Xtrem",
    location: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-07-17",
    distanceKm: 176,
    elevationGainM: 11590,
    terrainType: "Montagne / Massifs",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 3120,
    lastFinisherTimeMinutes: 3000,
    medianFinisherTimeMinutes: 2500,
    aidStationsCount: 12,
    priceEur: 250,
    description: "Ultra très engagé autour des massifs grenoblois, avec un dénivelé considérable et une gestion longue durée.",
    tags: ["Grenoble", "Ultra", "Massifs"],
    gradient: "from-slate-950 via-purple-800 to-sky-300"
  },
  {
    id: 32,
    name: "UT4M - 100 Master",
    location: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-07-18",
    distanceKm: 98,
    elevationGainM: 5860,
    terrainType: "Montagne / Massifs",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1680,
    lastFinisherTimeMinutes: 1600,
    medianFinisherTimeMinutes: 1280,
    aidStationsCount: 8,
    priceEur: 170,
    description: "Format 100K montagneux autour de Grenoble, très intéressant pour coureurs visant un ultra alpin.",
    tags: ["100K", "Grenoble", "Montagne"],
    gradient: "from-indigo-950 via-blue-800 to-lime-300"
  },
  {
    id: 33,
    name: "L’Échappée Belle - Intégrale",
    location: "Vizille → Aiguebelle",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-08-21",
    distanceKm: 152,
    elevationGainM: 11390,
    terrainType: "Alpin / Technique",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 3240,
    lastFinisherTimeMinutes: 3120,
    medianFinisherTimeMinutes: 2600,
    aidStationsCount: 10,
    priceEur: 235,
    description: "Traversée très technique du massif de Belledonne, réputée pour son engagement, ses pierriers et son altitude.",
    tags: ["Belledonne", "Extrême", "Technique"],
    gradient: "from-zinc-950 via-slate-700 to-rose-300"
  },
  {
    id: 34,
    name: "L’Échappée Belle - Traversée Nord",
    location: "Allevard → Aiguebelle",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-08-22",
    distanceKm: 96,
    elevationGainM: 7200,
    terrainType: "Alpin / Technique",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 1920,
    lastFinisherTimeMinutes: 1840,
    medianFinisherTimeMinutes: 1500,
    aidStationsCount: 7,
    priceEur: 150,
    description: "Format plus court que l’Intégrale mais très dense et technique, avec un vrai caractère haute montagne.",
    tags: ["Belledonne", "Technique", "D+ massif"],
    gradient: "from-slate-950 via-stone-700 to-orange-300"
  },
  {
    id: 35,
    name: "Trail du Ventoux - 75 km",
    location: "Bédoin",
    region: "Provence-Alpes-Côte d’Azur",
    date: "2026-03-28",
    distanceKm: 75,
    elevationGainM: 3900,
    terrainType: "Montagne / Provence",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 960,
    lastFinisherTimeMinutes: 920,
    medianFinisherTimeMinutes: 760,
    aidStationsCount: 6,
    priceEur: 95,
    description: "Grand format autour du Ventoux, exigeant par ses longues montées, ses crêtes et son exposition météo.",
    tags: ["Ventoux", "Technique", "D+"],
    gradient: "from-orange-950 via-red-700 to-yellow-300"
  },
  {
    id: 36,
    name: "Trail du Ventoux - 50 km",
    location: "Bédoin",
    region: "Provence-Alpes-Côte d’Azur",
    date: "2026-03-29",
    distanceKm: 50,
    elevationGainM: 2500,
    terrainType: "Montagne / Provence",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 660,
    lastFinisherTimeMinutes: 630,
    medianFinisherTimeMinutes: 510,
    aidStationsCount: 4,
    priceEur: 70,
    description: "Format long et nerveux au pied du Ventoux, bon test pour les coureurs visant du trail montagneux.",
    tags: ["Ventoux", "50K", "Montagne"],
    gradient: "from-amber-950 via-orange-700 to-lime-300"
  },
  {
    id: 37,
    name: "Volvic Volcanic Experience - XGTV",
    location: "Volvic",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-13",
    distanceKm: 224,
    elevationGainM: 8400,
    terrainType: "Volcanique / Ultra",
    technicalityLevel: "Extrême",
    cutoffTimeMinutes: 3600,
    lastFinisherTimeMinutes: 3450,
    medianFinisherTimeMinutes: 2850,
    aidStationsCount: 10,
    priceEur: 260,
    description: "Très long ultra volcanique, davantage centré sur l’endurance et l’autonomie que sur la technicité pure.",
    tags: ["Volcans", "Très long", "Autonomie"],
    gradient: "from-stone-950 via-red-800 to-lime-300"
  },
  {
    id: 38,
    name: "Volvic Volcanic Experience - 110 km",
    location: "Volvic",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-15",
    distanceKm: 110,
    elevationGainM: 3500,
    terrainType: "Volcanique / Forêt",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1560,
    lastFinisherTimeMinutes: 1480,
    medianFinisherTimeMinutes: 1150,
    aidStationsCount: 8,
    priceEur: 140,
    description: "Ultra volcanique varié dans la Chaîne des Puys, exigeant par la distance et les relances.",
    tags: ["Volcans", "100K", "Forêt"],
    gradient: "from-black via-stone-700 to-green-300"
  },
  {
    id: 39,
    name: "Trail de Haute Provence - THP80",
    location: "Ongles / Forcalquier",
    region: "Provence-Alpes-Côte d’Azur",
    date: "2026-05-16",
    distanceKm: 80,
    elevationGainM: 3400,
    terrainType: "Provence / Montagne",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1380,
    lastFinisherTimeMinutes: 1310,
    medianFinisherTimeMinutes: 1010,
    aidStationsCount: 7,
    priceEur: 120,
    description: "Trail provençal long, avec chaleur potentielle, sentiers secs et gestion de l’hydratation importante.",
    tags: ["Provence", "80K", "Chaleur"],
    gradient: "from-orange-950 via-amber-700 to-lime-300"
  },
  {
    id: 40,
    name: "Trail de Haute Provence - THP50",
    location: "Montlaux / Forcalquier",
    region: "Provence-Alpes-Côte d’Azur",
    date: "2026-05-16",
    distanceKm: 50,
    elevationGainM: 1700,
    terrainType: "Provence / Sentiers",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 660,
    lastFinisherTimeMinutes: 625,
    medianFinisherTimeMinutes: 485,
    aidStationsCount: 4,
    priceEur: 90,
    description: "Format long mais relativement accessible, bon compromis pour découvrir la Haute Provence en trail.",
    tags: ["50K", "Provence", "Accessible long"],
    gradient: "from-yellow-950 via-orange-700 to-emerald-300"
  },
  {
    id: 41,
    name: "Pilatrail - Traversée des Chirats",
    location: "Véranne",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-30",
    distanceKm: 92,
    elevationGainM: 5000,
    terrainType: "Montagne / Forêt",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1500,
    lastFinisherTimeMinutes: 1430,
    medianFinisherTimeMinutes: 1150,
    aidStationsCount: 7,
    priceEur: 115,
    description: "Ultra du Pilat exigeant, avec un fort ratio D+/km et des sections forestières techniques.",
    tags: ["Pilat", "Ultra", "D+"],
    gradient: "from-green-950 via-emerald-700 to-stone-300"
  },
  {
    id: 42,
    name: "Pilatrail - Tour des Crêts",
    location: "Véranne",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-05-31",
    distanceKm: 42,
    elevationGainM: 2400,
    terrainType: "Montagne / Forêt",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 570,
    lastFinisherTimeMinutes: 540,
    medianFinisherTimeMinutes: 430,
    aidStationsCount: 4,
    priceEur: 60,
    description: "Marathon trail très dense en dénivelé, idéal pour préparer les formats montagne courts et raides.",
    tags: ["Marathon", "Pilat", "D+"],
    gradient: "from-emerald-950 via-lime-700 to-yellow-300"
  },
  {
    id: 43,
    name: "Ultra du Saint-Jacques by UTMB",
    location: "Saugues → Le Puy-en-Velay",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-06-12",
    distanceKm: 139,
    elevationGainM: 6000,
    terrainType: "Chemins / Montagne",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1850,
    lastFinisherTimeMinutes: 1780,
    medianFinisherTimeMinutes: 1420,
    aidStationsCount: 9,
    priceEur: 190,
    description: "Ultra au profil sauvage sur les chemins de Saint-Jacques, avec un vrai enjeu de gestion nocturne.",
    tags: ["UTMB Index", "Saint-Jacques", "100M"],
    gradient: "from-stone-950 via-red-800 to-orange-300"
  },
  {
    id: 44,
    name: "Grand Trail du Saint-Jacques",
    location: "Monistrol-d’Allier → Le Puy-en-Velay",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-06-13",
    distanceKm: 86,
    elevationGainM: 3500,
    terrainType: "Chemins / Moyenne montagne",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1070,
    lastFinisherTimeMinutes: 1020,
    medianFinisherTimeMinutes: 810,
    aidStationsCount: 6,
    priceEur: 130,
    description: "Format 100K réduit, exigeant mais moins extrême que l’Ultra, intéressant pour une progression vers le très long.",
    tags: ["100K", "Saint-Jacques", "Progression"],
    gradient: "from-red-950 via-orange-700 to-yellow-300"
  },
  {
    id: 45,
    name: "Festival des Templiers - Grand Trail des Templiers",
    location: "Millau",
    region: "Occitanie",
    date: "2026-10-18",
    distanceKm: 80.7,
    elevationGainM: 3443,
    terrainType: "Causses / Falaises / Forêt",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 900,
    lastFinisherTimeMinutes: 860,
    medianFinisherTimeMinutes: 690,
    aidStationsCount: 4,
    priceEur: 115,
    description: "Course historique du trail français, entre causse, sentiers techniques, falaises et ambiance mythique à Millau.",
    tags: ["Mythique", "Millau", "Technique"],
    gradient: "from-amber-950 via-orange-800 to-red-300"
  },
  {
    id: 46,
    name: "Festival des Templiers - Endurance Trail",
    location: "Millau",
    region: "Occitanie",
    date: "2026-10-16",
    distanceKm: 99.5,
    elevationGainM: 4288,
    terrainType: "Causses / Falaises / Forêt",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1200,
    lastFinisherTimeMinutes: 1140,
    medianFinisherTimeMinutes: 900,
    aidStationsCount: 6,
    priceEur: 130,
    description: "Format long du Festival des Templiers, plus orienté ultra avec une forte exigence musculaire.",
    tags: ["Templiers", "100K", "Causses"],
    gradient: "from-stone-950 via-orange-700 to-yellow-300"
  },
  {
    id: 47,
    name: "SaintéLyon",
    location: "Saint-Étienne → Lyon",
    region: "Auvergne-Rhône-Alpes",
    date: "2026-11-28",
    distanceKm: 80,
    elevationGainM: 2400,
    terrainType: "Nocturne / Chemins / Route",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 960,
    lastFinisherTimeMinutes: 920,
    medianFinisherTimeMinutes: 710,
    aidStationsCount: 6,
    priceEur: 105,
    description: "Grande classique nocturne, difficile par le froid, la nuit, la boue possible et la gestion de l’allure.",
    tags: ["Nocturne", "Classique", "Hiver"],
    gradient: "from-indigo-950 via-slate-800 to-orange-300"
  },
  {
    id: 48,
    name: "Tarn Valley Trail - Intégrale des Gorges du Tarn",
    location: "Quézac → Millau",
    region: "Occitanie",
    date: "2026-05-02",
    distanceKm: 100,
    elevationGainM: 4200,
    terrainType: "Gorges / Causses",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1380,
    lastFinisherTimeMinutes: 1310,
    medianFinisherTimeMinutes: 1030,
    aidStationsCount: 7,
    priceEur: 130,
    description: "Ultra entre Lozère et Aveyron, alternant gorges, causses, sentiers techniques et paysages très ouverts.",
    tags: ["Gorges du Tarn", "100K", "Causses"],
    gradient: "from-lime-950 via-emerald-700 to-orange-300"
  },
  {
    id: 49,
    name: "Tarn Valley Trail - Marathon des Gorges du Tarn",
    location: "Saint-Rome-de-Dolan → Millau",
    region: "Occitanie",
    date: "2026-05-02",
    distanceKm: 44.5,
    elevationGainM: 1767,
    terrainType: "Gorges / Causses",
    technicalityLevel: "Soutenue",
    cutoffTimeMinutes: 480,
    lastFinisherTimeMinutes: 455,
    medianFinisherTimeMinutes: 360,
    aidStationsCount: 3,
    priceEur: 52,
    description: "Marathon trail esthétique dans les Gorges du Tarn, avec un dénivelé sérieux mais un temps limite relativement accessible.",
    tags: ["Marathon", "Gorges", "Occitanie"],
    gradient: "from-emerald-950 via-lime-700 to-yellow-300"
  },
  {
    id: 50,
    name: "Trail des Citadelles - 74 km",
    location: "Lavelanet",
    region: "Occitanie",
    date: "2026-04-05",
    distanceKm: 74,
    elevationGainM: 3400,
    terrainType: "Moyenne montagne / Sentiers",
    technicalityLevel: "Difficile",
    cutoffTimeMinutes: 1020,
    lastFinisherTimeMinutes: 970,
    medianFinisherTimeMinutes: 780,
    aidStationsCount: 6,
    priceEur: 85,
    description: "Trail ariégeois exigeant, avec montées longues, sentiers parfois boueux et ambiance de moyenne montagne.",
    tags: ["Ariège", "Difficile", "Moyenne montagne"],
    gradient: "from-red-950 via-orange-800 to-lime-300"
  }
];

export const levelWeights = { Reprise: 0.72, Régulier: 0.88, Confirmé: 1.05, Expert: 1.22 };

export const terrainPenalty = {
  Plat: { Mixte: 0, Montagne: -9, Nocturne: -7, Forêt: -2 },
  Vallonné: { Mixte: 4, Montagne: -4, Nocturne: -3, Forêt: 3 },
  Forêt: { Mixte: 4, Montagne: -5, Nocturne: -3, Forêt: 5 },
  Montagne: { Mixte: 6, Montagne: 9, Nocturne: 1, Forêt: 5 },
  Mixte: { Mixte: 6, Montagne: 1, Nocturne: 0, Forêt: 4 },
};
