export const races = [
  { id: 1, name: "Trail des Flandres", location: "Bailleul", region: "Hauts-de-France", date: "2026-04-18", distanceKm: 42, elevationGainM: 950, terrainType: "Mixte", technicalityLevel: "Modérée", cutoffTimeMinutes: 600, lastFinisherTimeMinutes: 572, medianFinisherTimeMinutes: 430, aidStationsCount: 4, priceEur: 48, description: "Trail vallonné typique des Flandres, alternant chemins agricoles, sentiers boisés, montées courtes et passages potentiellement boueux.", tags: ["Idéal reprise", "Barrières larges"], gradient: "from-emerald-900 via-lime-700 to-orange-300" },
  { id: 2, name: "Ultra Vosgien", location: "Gérardmer", region: "Grand Est", date: "2026-06-27", distanceKm: 72, elevationGainM: 3200, terrainType: "Montagne", technicalityLevel: "Difficile", cutoffTimeMinutes: 960, lastFinisherTimeMinutes: 942, medianFinisherTimeMinutes: 760, aidStationsCount: 7, priceEur: 92, description: "Parcours exigeant de moyenne montagne, avec longues montées, descentes techniques et gestion de l’effort sur la durée.", tags: ["Prépa ultra", "Technique"], gradient: "from-slate-900 via-emerald-800 to-cyan-300" },
  { id: 3, name: "Marathon des Crêtes", location: "Le Tholy", region: "Grand Est", date: "2026-09-20", distanceKm: 42, elevationGainM: 1900, terrainType: "Montagne", technicalityLevel: "Soutenue", cutoffTimeMinutes: 510, lastFinisherTimeMinutes: 478, medianFinisherTimeMinutes: 380, aidStationsCount: 5, priceEur: 55, description: "Format marathon très dense en dénivelé, adapté aux coureurs déjà à l’aise sur terrain technique et descentes longues.", tags: ["Technique", "Crêtes"], gradient: "from-stone-900 via-orange-700 to-amber-300" },
  { id: 4, name: "Trail des Flandres Ultra", location: "Bailleul", region: "Hauts-de-France", date: "2026-04-18", distanceKm: 115, elevationGainM: 2800, terrainType: "Mixte", technicalityLevel: "Difficile", cutoffTimeMinutes: 1440, lastFinisherTimeMinutes: 1395, medianFinisherTimeMinutes: 1120, aidStationsCount: 10, priceEur: 125, description: "Ultra long et usant, moins montagneux qu’un alpin mais exigeant par la durée, la météo possible et la répétition des relances.", tags: ["Ultra", "Gestion chrono"], gradient: "from-emerald-950 via-emerald-700 to-lime-300" },
  { id: 5, name: "SaintéLyon", location: "Saint-Étienne → Lyon", region: "Auvergne-Rhône-Alpes", date: "2026-12-05", distanceKm: 78, elevationGainM: 2100, terrainType: "Nocturne", technicalityLevel: "Soutenue", cutoffTimeMinutes: 960, lastFinisherTimeMinutes: 940, medianFinisherTimeMinutes: 710, aidStationsCount: 6, priceEur: 98, description: "Course mythique de nuit, roulante par moments mais piégeuse par le froid, la fatigue et les longues portions nocturnes.", tags: ["Nocturne", "Mythique"], gradient: "from-indigo-950 via-slate-800 to-orange-300" },
  { id: 6, name: "Trail du Jura", location: "Les Rousses", region: "Bourgogne-Franche-Comté", date: "2026-07-11", distanceKm: 55, elevationGainM: 2400, terrainType: "Montagne", technicalityLevel: "Difficile", cutoffTimeMinutes: 720, lastFinisherTimeMinutes: 698, medianFinisherTimeMinutes: 545, aidStationsCount: 5, priceEur: 69, description: "Format intermédiaire parfait pour progresser vers le long, avec un ratio D+/km sérieux et un terrain parfois cassant.", tags: ["Étape intermédiaire", "D+"], gradient: "from-sky-950 via-emerald-700 to-lime-200" },
];

export const levelWeights = { Reprise: 0.72, Régulier: 0.88, Confirmé: 1.05, Expert: 1.22 };

export const terrainPenalty = {
  Plat: { Mixte: 0, Montagne: -9, Nocturne: -7, Forêt: -2 },
  Vallonné: { Mixte: 4, Montagne: -4, Nocturne: -3, Forêt: 3 },
  Forêt: { Mixte: 4, Montagne: -5, Nocturne: -3, Forêt: 5 },
  Montagne: { Mixte: 6, Montagne: 9, Nocturne: 1, Forêt: 5 },
  Mixte: { Mixte: 6, Montagne: 1, Nocturne: 0, Forêt: 4 },
};
